### ISSUE TITLE
[STEAMID] Wrong steam ID

### ISSUE THREAD

**Issue by fahrenheit93** [nickbabcock/rrrocket#2]
Hello,

i recently found something wrong with properties, the steam id is not the same as the real one.

Example here : 
![image](https://user-images.githubusercontent.com/48847643/56612805-8c8e6780-6615-11e9-8e14-f356d3155f2b.png)

And the real one : 
![image](https://user-images.githubusercontent.com/48847643/56612843-9dd77400-6615-11e9-9fe2-7723a17a22ee.png)

Thank you.

PS : It seem that i have to add +2 to the id to get the real one, tested with two players

**Comment by nickbabcock** [comment]
This is due to numbers in javascript being double precision (ie floating point). These numbers are unable to represented correctly (if you type `76561198122624102` into the browser console, it will display `76561198122624100`). Don't worry, checking on this issue tripped me up as I run the output of rrrocket through [`jq`](https://github.com/stedolan/jq) to prettify it and jq rounds the numbers too 😅 

So `rrrocket` is outputting the correct id (76561198122624102). Whatever is interpreting in your screenshot is "wrong". I put "wrong" in quotes as I think it may be better for the steam id output to be a string instead of a number so there is no room for misinterpretation 😄 

How does that sound?

**Comment by fahrenheit93** [comment]
That's a perfect response thank you !

Here it is : 
![image](https://user-images.githubusercontent.com/48847643/56651361-25aa9600-6689-11e9-9dfd-3a29ab50920a.png)

**Comment by nickbabcock** [comment]
Glad to hear! Do you think that outputting the steam id (and other 64bit integers) as strings is a better long term solution, so one doesn't have to use specialized json libraries?

**Comment by fahrenheit93** [comment]
String would be very nice i think yes for this types of long int imo

**Comment by nickbabcock** [comment]
Check out v0.2.10. I released it 3 days ago and writes 64bit integers as strings. Let me know how you like it
!
